### PR TITLE
Add --services option

### LINKED ISSUE #98: Feature request of Former2 CLI: Select services
I often use Former2 CLI in the AWS Accounts with a lot of resources and services. 
So I would like to not only exclude services but also select specific services with the command line options to generate outputs.

### PR DESCRIPTION
**Pull request by jlandowner**
Close #98

### CODE REVIEW

**Comment by iann0036** [comment]
For consistency, would you be happy with `--include-services` ?

**Comment by jlandowner** [comment]
I think `former2 generate --services EC2 --output-cloudformation cfn.yaml` is more clear than `former2 generate --include-services EC2 --output-cloudformation cfn.yaml` for meaning that 'it generate ALL services by default, but it can generate the specified services when using the flag'.

I feel the output will have something other than specified services for `--include-services`.

What do you think about it?

**Comment by iann0036** [comment]
Yeah, that's fine.

Merged and published to npm as v0.2.50.

**Comment by jlandowner** [comment]
I really appreciate your review!

**Comment by rshedzer** [comment]
Is there a list of services for this? I can't seem to get the CLI to output cognito users. I've tried `former2 generate --services "Cognito"  --output-cloudformation "cognito.yaml" --region us-east-1 --debug` and other variations including listing all the column mappings found in services/cognito.js and no dice. I'm using the npm installed version, but maybe should use the docker one?

**Pull request merged**
