### PR TITLE
Adds an option to output a logical to physical ID mapping when using …

### PR DESCRIPTION
**Pull request by mbenz89**
…the CLI to generate CloudFormation files. This helps to keep track of which CloudFormation resources actually correspond the resources running in AWS for external tools.

### CODE REVIEW

**Comment by mbenz89** [comment]
@iann0036 Sorry for the late reply and thanks for your fixes!

Unfortunately, the escaping proposed in https://github.com/iann0036/former2/commit/d81418335fb86b4f722e9c7d32ec3820d9b4254d is not quite sufficient to solve https://github.com/iann0036/former2/issues/174#issuecomment-907067836.

I hereby propose a different solution for yaml-string escaping based on https://github.com/eemeli/yaml. 

Please let me know if this makes sense to you. I am especially not sure about the handlings for pulumi, cdk, boto, etc. This escaping is targeted towards yaml output and therefore especially important when generating CloudFormation files.

Tested with my own AWS environment and worked as intended there.

**Comment by mbenz89** [comment]
Also please let me know if I should separate the PR in multiple ones again. seems like this PR is now containing all proposals:

- string escaping
- logical to physical id output
- remove restrictions on  upper bound for logical ids

**Comment by iann0036** [comment]
Hey @mbenz89,

Happy with all of the above. Appreciate the work!

**Comment by iann0036** [comment]
Published as 0.2.58 on npm.

**Pull request merged**
