### PR TITLE
Changed search-filter to regexp and new filter command to work with saved raw data

### PR DESCRIPTION
**Pull request by vseryakov**
Hi,

Using regexp for filtering what to save can be more flexible in what to keep, in my case i need to save CFN as backups but do not need resources which are launch by Autoscaling groups, for example.

Playing around also took a lot of scans so i added new filter command to experiment with filters using local raw data file.

Also loading region from .aws/credentials like AWS CLI is added as well

Thank you

### CODE REVIEW

**Comment by iann0036** [comment]
Hey @vseryakov,

Thanks for the contribution. I think a few people have taken a dependency on the old search behaviour. Would it be possible to branch this logic off into a new CLI arg, say, `--regex-filter` or something?

**Comment by vseryakov** [comment]
sure, this is a good idea

**Review by iann0036 — APPROVED** [review]

**Comment by iann0036** [comment]
Hi @vseryakov,

Thanks again for your contribution. This has been published to npm as version 0.2.79.

**Comment by vseryakov** [comment]
Yay! thanks

i have a couple of more ideas because i am using it for my work....to be continued

**Pull request merged**
