### PR TITLE
Added List Resources (html table), Added Select Resources by Tag

### PR DESCRIPTION
**Pull request by cairnswm**
For my project I needed a list of resources so the rest of my team could identify which resources should be included into the generated CloudFormation Template

### CODE REVIEW

**Comment by iann0036** [comment]
Hi @cairnswm,

Thanks for your contribution.

Unfortunately, I don't think this is a feature I'd like to add, at least in the way you've laid it out. Former2 already has a search feature which will be able to provide a list of resources based on arbitrary values including tags and I'd like to keep the top bar clear of potentially confusing items. I believe an empty search would also produce all results.

Does the search bar not provide what you need specifically and if not, is there maybe a way we can add detailed search to the https://former2.com/#section-search page instead?

**Comment by cairnswm** [comment]
When I first used the search it did not limit to just the objects I wanted - ie those only with the value in the tags. I could change my tags to be more specific\ so that they are not repeated in any other field.  (ie don't use abbreviations)

How would I get a lit of all resources so my team can mark which items are needed? (Our account currently has over 1400 resources)

**Comment by cairnswm** [comment]
Ahh it does list all resources on a blank search. Just takes a long time :)

**Comment by iann0036** [comment]
If you perform an Account Scan (the button is more visible just recently) then do a search for nothing (just hit Enter in the field) it should give you a list of everything in the account.

I've just done a couple of minor changes that should make these results return much faster - I easily loaded ~900 resources myself. You might have to refresh your cache for that to take effect. You can also do the arbitrary search for your tag value to reduce the list a bit.

**Comment by cairnswm** [comment]
Thanks for the feedback :)

Can I ask how the related resources work? When I add a lambda the related permissions (resource based policy) is not added.

**Comment by iann0036** [comment]
To be honest that probably needs a little more work.

In order to avoid circular dependancies, the relationship graph currently only goes one direction so though you may get a prompt for related resources when you add the permission it might not work the other way. For example, after an account scan I get recommendations about the attached roles of my Lambda Functions, but not those permissions (usually).

Certainly something I'll look at improving shortly.

**Comment by cairnswm** [comment]
Is there a way I can help?

I also notice that each associated resource is listed twice in the suggestion list.

(A select all checkbox in the related items might be nice ;) )

**Comment by iann0036** [comment]
The relevant function starts here (https://github.com/iann0036/former2/blob/master/js/app.js#L114).

It looks like I already tried deduplicating but obviously failed (https://github.com/iann0036/former2/blob/master/js/app.js#L165-L181) so if you want to have a crack at a fix for that, that'd be great.

If you can also get the Select All in there neatly, feel free.

The circular relationship happens elsewhere so I might have a go at that myself.

**Comment by iann0036** [comment]
Hey @cairnswm,

It turns out the circular relationship code is also associated with that area of code, so I ended up fixing the deduplication code as per (https://github.com/iann0036/former2/commit/55e63c60148493c6ec23f0281c0e32c805f139d2).

Happy if you still want to do Select All?

**Comment by cairnswm** [comment]
Should this code not be inside the !is_duplicate

                                                    if (!Array.isArray(related_resources[readable_relationship_type])) {
                                                        related_resources[readable_relationship_type] = [];
                                                    }

You may clear the data and never repopulate

**Comment by cairnswm** [comment]
Lambda:Function has no property that points to the Lambda:Permission - from my revue of the code there is no reverse-relationship option (ie check each Permission for a property pointing back to the Function).

Am I right?

**Comment by iann0036** [comment]
I did eventually get the reverse relationship working as per this huge change (https://github.com/iann0036/former2/commit/d70411637104f00af2f43da538b753c2ab6f113b).

Give the permission suggestion a shot now?

**Comment by cairnswm** [comment]
Fantastic, worked first time :)

Is there another place we can chat. This thread is way off topic ;)

Is there a way I can tell it to change the object names. We have one account and need to duplicate our environment for different demos. We use a prefix eg FS_ or WC_ in front of each object. I'd like to import the FS_ (as this environment is configured correctly) and replace with WC_. I know I can do it in the YAML afterwards.

**Comment by iann0036** [comment]
Best place to find me is via DM on Twitter [@iann0036 ](https://twitter.com/iann0036) or via some of the AWS Slack channels.

For the prefix change, I recommend adding a parameter via the Settings > Parameters section and making `FS_` the default value. This will replace those values with the parameter variable on next generation, which you can change per stack.

**Pull request closed without merging**
